### PR TITLE
New Frontend

### LINKED ISSUE #114: Visual Bugs
The frontend contains a lot of minor visual bugs due to my bad CSS.
This is an issue tracking those.  All of these I am accepting of any idea or approach of making it cleaner. 

- [ ] The collapsing of the horizontal menus through out Admin Panel 
image
- [ ] Some of the menus create this ugly length. 
image

### PR DESCRIPTION
**Pull request by wherkamp**
- [x] View Repositries https://github.com/wherkamp/nitro_repo/pull/223#issuecomment-1065147208
- [x] View Storages
- [x] View Users 
- [x] Basic View Project Page https://github.com/wherkamp/nitro_repo/pull/223#issuecomment-1066220407
- [x] Basic View Repository Page https://github.com/wherkamp/nitro_repo/pull/223#issuecomment-1066153813
- [x] Admin Create Usershttps://github.com/wherkamp/nitro_repo/pull/223#issuecomment-1067991156
- [x] Admin Create Repositories
- [x] Admin Create Storages
- [x] Browse 
- [x] Login https://github.com/wherkamp/nitro_repo/pull/223#issuecomment-1001157986
- [x] Update Users https://github.com/wherkamp/nitro_repo/pull/223#issuecomment-1068232906
- [x] Update Repositories
- [x] View Storage Info
- [x] New Installer https://github.com/wherkamp/nitro_repo/pull/321

Replaces Element Plus with a New Frontend done with tailwindcss.

Closes #114

### CODE REVIEW

**Comment by wherkamp** [comment]
firefox_2021-12-26_06-05-35
firefox_2021-12-26_05-56-36

**Comment by wherkamp** [comment]
image

**Comment by wherkamp** [comment]
image

**Comment by wherkamp** [comment]
image

**Comment by wherkamp** [comment]
https://user-images.githubusercontent.com/11785959/157883639-6b785240-1b3a-43fa-ab83-42ec2c43a08b.mp4

**Comment by wherkamp** [comment]
image

**Comment by wherkamp** [comment]
https://media.discordapp.net/attachments/403685774362411021/952234922767175720/unknown.png?width=879&height=315

**Comment by wherkamp** [comment]
image

**Comment by wherkamp** [comment]
https://user-images.githubusercontent.com/11785959/158070062-38a57a63-190b-4f24-ac0c-1772c1d4b7a3.mp4

Repository Details

**Comment by wherkamp** [comment]
image

**Comment by wherkamp** [comment]
image

**Comment by JasonTaylor234u** [comment]
This looks Good!!

**Comment by wherkamp** [comment]
https://user-images.githubusercontent.com/11785959/158227373-14753b24-2524-45d3-ba80-4752c0d21d39.mp4

**Comment by wherkamp** [comment]
image

**Comment by wherkamp** [comment]
image
My worst looking page so far.

**Pull request merged**
